### ISSUE TITLE
problems using csh as default login shell when launching graphical session

### ISSUE THREAD

**Issue by gmc99** [awslabs/scale-out-computing-on-aws#25] opened 2020-07-09 08:29 UTC
I've added a user to the LDAP account and changed the loginShell to be /bin/csh (all my env setup scripts are for csh) - when I try to launch a graphical access session I get the following error -

Error while trying to launch your session: Please verify you can submit job to the desktop queue. Error:
b'su: failed to execute /bin/csh: No such file or directory\n'

version - SOCA AWS 2.0.1

with loginShell as /bin/bash it launches as expected.

**Comment by mcrozes** [comment] 2020-07-09 12:32
Hello @gmc99 -

Seems like `tcsh` is not installed on your environment. On your desktop machine, execute `yum install -y tcsh` to install `/bin/csh`.

Note this is a one time command and won't apply to any future nodes your system will deploy. To make this change permanent:

1.  Add  yum install -y tcsh on https://github.com/awslabs/scale-out-computing-on-aws/blob/master/source/soca/cluster_node_bootstrap/ComputeNodeUserCustomization.sh
2. Create your own AMI with tcsh already installed (instructions: https://awslabs.github.io/scale-out-computing-on-aws/tutorials/reduce-compute-node-launch-time-with-custom-ami/)

**Comment by gmc99** [comment] 2020-07-09 12:49
Hi @mcrozes 
you're right! - what was confusing was it was the scheduler that was missing the tcsh - I was using a pre-built AMI with tsch in for the main machines

thanks for your help

**Comment by gmc99** [comment] 2020-07-16 09:55
Hi,
I still have problems launching graphical access with a users login shell set to /bin/csh. The scheduler is running the standard Centos7 image + /bin/csh and when I run a graphical access request it returns with 502 Bad Gateway. On the scheduler it hasn't queued a desktop job and there are a couple of processes still hanging around running under the owners name.

```
ab      10466     1  0 07:48 ?        00:00:00 csh -c /opt/pbs/bin/qsub <<EOF #PBS -N Desktop1 #PBS -q desktop #PBS -P gui #PBS -l walltime=24:00:00 #PBS -l instance_type=m5.large #PBS -e /dev/null #PBS -o /dev/null # Create the DCV Session /usr/bin/dcv create-session --user  ab --owner ab 91d2c5c0-5aa0-40bd-be1e-2c45d8151b4b  # Query dcvsimpleauth with add-user echo MzdpeXZUWVZNSGRoOXBFRmVCRlRETnhrNndRSE9lcmdLVTFCRXd2Mm85aG5SYmZMZFlSaFlCamY3czRRRFZLallZd2V2ZHpaN2RUeEtORks= | base64 --decode | /usr/libexec/dcvsimpleextauth.py add-user --user ab --session 91d2c5c0-5aa0-40bd-be1e-2c45d8151b4b --auth-dir /var/run/dcvsimpleextauth  # Uncomment if you want to disable Gnome Lock Screen (require webui restart) # GSETTINGS=$(which gsettings) # $GSETTINGS set org.gnome.desktop.lockdown disable-lock-screen true # $GSETTINGS set org.gnome.desktop.session idle-delay 0  # Keep job open while true     do         session_keepalive=$(/usr/bin/dcv list-sessions | grep 91d2c5c0-5aa0-40bd-be1e-2c45d8151b4b | wc -l)         if [ $session_keepalive -ne 1 ]             then                 exit 0         fi         sleep 3600     done EOF 
ab      10483 10466  0 07:48 ?        00:00:00 sleep 3600
```




I have been able to get around this by modifying the dcv.py command to include '--shell=/bin/bash' into run_jobcommand. This forces the command above to launch with bash which means that the job is launched and appears on the queue. The machine starts but then terminates - I've not been able to debug this further. It loads a CN up and then tries to start a dcv session and launches X but quickly dies. Extract of ps on CN -

```
ab        2989  2986  0 08:55 ?        00:00:00 /bin/bash /usr/libexec/dcv/dcvsessionstarter
ab        3021  2919  0 08:55 ?        00:00:00 /opt/pbs/sbin/pbs_mom
ab        3070  2989  0 08:55 ?        00:00:00 /usr/bin/Xdcv -sessionid 91ceb949-1f37-4155-ae25-87f61523d8e9 -auth /run/user/5004/dcv/91ceb949-1f37-4155-ae25-87f61523d8e9.xauth -displayfd 4 -output 800x600+0+0 -output 800x600+800+0 -output 800x600+1600+0 -output 800x600+2400+0 -enabledoutputs 1 -listen tcp -verbose 3 -dpi 96
ab        3080  2989  0 08:55 ?        00:00:00 /usr/libexec/dcv/dcvagent --session-id 91ceb949-1f37-4155-ae25-87f61523d8e9 --display :1 --settings-path /etc/dcv/dcv.conf --log-level info --log-dir /var/log/dcv --log-rotate 10 --backends input,pointer,display,qi-monitor,clipboard,smartcard,filestorage,audio
ab        3089  2989  0 08:55 ?        00:00:00 /bin/sh /etc/dcv/dcvsessioninit 91ceb949-1f37-4155-ae25-87f61523d8e9
ab        3091     1  0 08:55 ?        00:00:00 dbus-launch --autolaunch=05cb8c7b39fe0f70e3ce97e5beab809d --binary-syntax --close-stderr
ab        3093     1  0 08:55 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 6 --print-address 8 --session
ab        3094  3089  0 08:55 ?        00:00:00 -/bin/csh -c  /usr/bin/ssh-agent /data/home/ab/.Xclients
ab        3250  3094  0 08:55 ?        00:00:00 /bin/sh /data/home/ab/.Xclients
ab        3251  3250  0 08:55 ?        00:00:00 /usr/bin/ssh-agent /data/home/ab/.Xclients
ab        3252  3250  0 08:55 ?        00:00:00 xfce4-session

```
thanks

**Comment by mcrozes** [comment] 2020-07-18 15:25
Hello -

According to your screen, the DCV sessions seems to be running fine, so I am not exactly sure what's triggering your HTTP/502.

I also checked on my side and everything is working as expected (with Amazon Linux 2)
<img width="1047" alt="csh+dcv" src="https://user-images.githubusercontent.com/1182095/87855847-04b30e00-c8e9-11ea-8424-58c557e2d101.png">

For me to try to reproduce your issue, can you let me know what region and AMI id you are using? If you are using a custom AMI (not the one provided by default with SOCA), make sure that you have disabled `firewalld`, `libvirtd` and `selinux` (if applicable)

**Comment by gmc99** [comment] 2020-07-20 09:36
Hi,
thanks for getting back. I have a custom AMI based on the Centos 7 package - ami-099e8526e67cc558f - I'm in eu-west-1. I have all three services disabled.  The AMI works perfectly if I use loginShell=/bin/bash.

![image](https://user-images.githubusercontent.com/68053546/87922607-1ffe5480-ca74-11ea-8b41-c7f0e7f8aa48.png)

thanks
Gerard

**Comment by mcrozes** [comment] 2020-07-25 22:39
Hey @gmc99  -

I was not able to locate your AMI, so I assume it's your private custom AMI, which will make thing hard to debug. We have recently pushed SOCA 2.5.0 (https://github.com/awslabs/scale-out-computing-on-aws/releases/tag/2.5.0) which provide native support for custom shell. Would it be possible to you to test it out ?

**Comment by gmc99** [comment] 2020-07-30 12:31
HI,
yes the AMI is a private custom AMI. Unfortunately the contract I'm on will be ending soon so I won't have time to test it out - unless at some point I am brought back to upgrade.
thanks for you help 
Gerard

**Comment by mcrozes** [comment] 2020-07-30 16:22
Hey @gmc99  -

Sounds good. I will go ahead and close this ticket. Feel free to re-open it in the future if needed

**Closed by mcrozes** 2020-07-30 16:22 UTC
